# Generated by Django 2.1 on 2018-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(choices=[('pms1', 'pms1'), ('pms2', 'pms2'), ('pms3', 'pms3'), ('ago1', 'ago1'), ('ago2', 'ago2'), ('ago3', 'ago3'), ('bik1', 'bik1'), ('bik2', 'bik2'), ('bik3', 'bik3')], max_length=20)),
                ('pump_category', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Kerosene', 'Kerosene')], max_length=20)),
                ('opening_reading', models.FloatField()),
                ('closing_reading', models.FloatField()),
                ('transfers', models.FloatField()),
            ],
        ),
    ]
