# Generated by Django 2.1 on 2018-12-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(choices=[('pms1', 'pms1'), ('pms2', 'pms2'), ('pms3', 'pms3'), ('ago1', 'ago1'), ('ago2', 'ago2'), ('ago3', 'ago3'), ('bik1', 'bik1'), ('bik2', 'bik2'), ('bik3', 'bik3')], max_length=20)),
                ('pump_category', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Kerosene', 'Kerosene')], max_length=20)),
                ('station_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelcard.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('opening_reading', models.FloatField()),
                ('closing_reading', models.FloatField()),
                ('meter_movement', models.FloatField()),
                ('transfers', models.FloatField()),
                ('net_sales', models.FloatField()),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelcard.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.CharField(choices=[('PMS', 'PMS'), ('TRUCK', 'TRUCK'), ('AGO', 'AGO'), ('BIK', 'BIK')], max_length=10)),
                ('opening_stock', models.FloatField()),
                ('product_received', models.FloatField()),
                ('product_returned', models.FloatField()),
                ('closing_stock', models.FloatField()),
            ],
        ),
    ]
