# Generated by Django 2.1 on 2018-10-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('opening_reading', models.FloatField()),
                ('closing_reading', models.FloatField()),
                ('transfers', models.FloatField()),
                ('net_sales', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pump',
            name='closing_reading',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='opening_reading',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='transfers',
        ),
        migrations.AddField(
            model_name='report',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelcard.Pump'),
        ),
    ]
