# Generated by Django 2.1 on 2018-12-19 14:46

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
