# Generated by Django 2.1 on 2018-10-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0002_auto_20181009_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='station_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
