# Generated by Django 2.1 on 2018-12-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0002_ratings_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
            ],
        ),
    ]
