# Generated by Django 2.1 on 2018-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0003_pump_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='meter_movement',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
