# Generated by Django 2.1 on 2018-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelcard', '0006_report_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.CharField(choices=[('PMS', 'PMS'), ('TRUCK', 'TRUCK'), ('AGO', 'AGO'), ('BIK', 'BIK')], max_length=10)),
                ('opening_stock', models.FloatField()),
                ('product_received', models.FloatField()),
                ('product_returned', models.FloatField()),
                ('closing_stock', models.FloatField()),
            ],
        ),
    ]
